### ISSUE TITLE
Update code field after button use

### ISSUE THREAD

**Issue by ceg9498** [umb-cs410-fritz/Authoring-Tool-for-Visual-Piling#27]
Problem: After using the columns slider, the code in the "Custom Code" panel does not update.

Should be: After interacting with a slider or button, the code in the "Custom Code" panel should update visually.

Reproduction Steps:

1. Select the "Styles" tab in the top-left
2. Check the value for "columns" in the "Custom Code" panel and the value for the "Columns" slider. (They match by default)
3. Adjust the "Columns" slider so that the value updates
4. Check the value for "columns" in the "Custom Code" panel. The values should match after a short update period.

**Comment by kntrjs** [comment]
it is updating.
